DROP TABLE BOOKINGS CASCADE CONSTRAINTS;
DROP TABLE CUSTOMERS CASCADE CONSTRAINTS;
DROP TABLE FLIGHTS CASCADE CONSTRAINTS;

DROP TRIGGER UPDATE_SEAT_ON_BOOKING;
DROP TRIGGER UPDATE_SEAT_ON_CANCELLATION;

COMMIT;